PainelPokemon/Controllers/PokemonController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PainelPokemon.Data;
using PainelPokemon.Models.Pokemons;
using PainelPokemon.Models.Users;
using PainelPokemon.Repositories;



namespace PainelPokemon.Controllers
{
    public class PokemonController : Controller
    {
        private readonly ILogger<PokemonController> _logger;

        private readonly IPokemonRepository _pokemonRepository;

        private readonly PokeContext _context;



        public PokemonController(ILogger<PokemonController> logger,IPokemonRepository pokemonRepository, PokeContext context)
        {
            _logger = logger;
            _pokemonRepository = pokemonRepository;
            _context=context;
        }


        [Route("/pokemon/favorite")]
        public async Task<IActionResult> favorite()
        {

            var userId = int.Parse(HttpContext.Session.GetString("UserId"));
            
            var favoritePokemons =  _context.FavoritePokemons.ToListAsync().Result.Where(x => x.UserId == userId);
            var pokemons = new List<PokemonUnity>();
            HttpClient client = new HttpClient();
            foreach (var pokemonResult in favoritePokemons)
            {
                System.Uri uri = new System.Uri($"https://pokeapi.co/api/v2/pokemon/{pokemonResult.PokemonUnityId}");
                var pokemon = _pokemonRepository.GetOne(uri, client);
                pokemons.Add(pokemon);
            }
            return View(pokemons);

            
        }
        [Route("/pokemon/RemoveFavorite")]
        public async Task<IActionResult> RemoveFavorite(int id)
        {
            var userId = int.Parse(HttpContext.Session.GetString("UserId"));
            var existingPokemon = await _context.FavoritePokemons.FirstOrDefaultAsync(p => p.PokemonUnityId == id && p.UserId == userId);
            Console.WriteLine(existingPokemon);
            if (existingPokemon != null) { 
                  _context.FavoritePokemons.Remove(existingPokemon);
                  await _context.SaveChangesAsync();

            }
            
           
            return Redirect("/pokemon/favorite");

        }






        [Route("/pokemon/Addfavorite")]
        public async Task<IActionResult> AddFavoritePokemon(int id)
        {
            var userId = int.Parse(HttpContext.Session.GetString("UserId"));
            var user = _context.Users.FirstOrDefault(x => x.Id == userId);

            HttpClient client = new HttpClient();
            System.Uri uri = new System.Uri($"https://pokeapi.co/api/v2/pokemon/{id}");

            var pokemonInfo =  _pokemonRepository.GetOne(uri, client);

            var existingPokemon = await _context.Pokemons.FirstOrDefaultAsync(p => p.Id == pokemonInfo.Id);
            if (existingPokemon == null)
            {
                
                _context.Pokemons.Add(pokemonInfo);
                await _context.SaveChangesAsync();
            }
            var favoritesPokemons = await _context.FavoritePokemons.FirstOrDefaultAsync(x=> x.PokemonUnityId == pokemonInfo.Id && x.UserId==userId);
            if (favoritesPokemons == null)
            {

                var favoritePokemon = new FavoritePokemon
                {
                    UserId = user.Id,
                    PokemonUnityId = pokemonInfo.Id
                };
                _context.FavoritePokemons.Add(favoritePokemon);
                await _context.SaveChangesAsync();
            }

            

            return Redirect("/pokemon/favorite");
        }



        [Route("")]
        public IActionResult Pokemons(string? urlPast)
        {


            var url= "https://pokeapi.co/api/v2/pokemon/?offset=0&limit=12";
            if (urlPast != null)
            {
                url = urlPast;
            }
            
            HttpClient client = new HttpClient();
            var pokemons = _pokemonRepository.GetAll(url,client);
            PokemonsResults pokemonResults = new PokemonsResults();
            pokemonResults.Pokemons=pokemons;

            foreach (var pokemonResult in pokemons.Results){

                var pokemon = _pokemonRepository.GetOne(pokemonResult.Url, client);
                pokemonResults.Pokemon.Add(pokemon);
            }
            return View(pokemonResults);    
        }
    }
}

PainelPokemon/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PainelPokemon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PainelPokemon.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Pokemon" asp-action="Pokemons">PainelPokemon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pokemon" asp-action="Pokemons">Home</a>
                        </li>

                        @{
                            var userId = @HttpContextAccessor.HttpContext.Session.GetString("UserId");
                        }


                        @if (!string.IsNullOrEmpty(userId))
                        {
                            <td>
                                <a class ="nav-link text-dark" asp-controller="Pokemon" asp-action="Favorite" asp-action="Favorite">
                                    Favoritos
                                </a>
                            </td>
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout" asp-action="Logout">
                                Sair
                            </a>
                        }
                        else
                        {
                            <td>
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login" asp-action="Login">
                                    Login
                                </a>
                            </td>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PainelPokemon - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>